name: GLuaLint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: npm for Lua lint
      run: |
        set +ex
        export PATH=$PATH:/tmp/bin
        mkdir -p /tmp/bin
        pushd /tmp/bin
        wget -q https://github.com/FPtje/GLuaFixer/releases/download/1.28.0/glualint-1.28.0-x86_64-linux.zip -O glualint.zip
        unzip glualint.zip
        chmod +x glualint
        popd
        echo "Running linter..."
        node gluaLintEx.js
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
